name: Angry Miner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Add this for manual execution

jobs:
  run-js-script:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install p-limit --no-bin-links
           npm install axios --no-bin-links
           npm install colors --no-bin-links
           npm install user-agents --no-bin-links
           npm install socks-proxy-agent --no-bin-links
           npm install https-proxy-agent --no-bin-links
           npm install uuid --no-bin-links

    - name: Run meomundep.js
      run: node meomundep.js
